server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:notificationdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://schema-registry:8081
        specific.avro.reader: true

kafka:
  topic:
    transaction-events: fin.transaction.events

eureka:
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,busrefresh