server:
  port: 8761

spring:
  application:
    name: eureka-server

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false