server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/wnsdn-tech/fin-account-config-repo.git

    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}