apiVersion: v1
kind: Secret
metadata:
  name: fin-account-secrets
  namespace: fin-account-hub
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "rootpassword"
  MARIADB_PASSWORD: "apppassword"
  MARIADB_USER: "appuser"
  MARIADB_DATABASE: "appdb"