apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-notification
  namespace: fin-account-hub
spec:
  serviceName: mariadb-notification
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-notification
  template:
    metadata:
      labels:
        app: mariadb-notification
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fin-account-secrets
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: fin-account-secrets
                  key: MARIADB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: fin-account-secrets
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fin-account-secrets
                  key: MARIADB_PASSWORD
          volumeMounts:
            - name: mariadb-notification-data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: mariadb-notification-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi