apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: fin-account-hub
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: uniquecolor/transaction-service:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fin-account-config
            - secretRef:
                name: fin-account-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mariadb://mariadb-transaction:3306/appdb"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5