apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fin-account-hub

resources:
  - ../../base

commonLabels:
  environment: dev

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: gateway
        namespace: fin-account-hub
      spec:
        replicas: 1
      target:
        kind: Deployment
        name: gateway
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: account-service
        namespace: fin-account-hub
      spec:
        replicas: 1
      target:
        kind: Deployment
        name: account-service
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: transaction-service
        namespace: fin-account-hub
      spec:
        replicas: 1
      target:
        kind: Deployment
        name: transaction-service
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: notification-service
        namespace: fin-account-hub
      spec:
        replicas: 1
      target:
        kind: Deployment
        name: notification-service

configMapGenerator:
  - name: fin-account-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev